### ISSUE TITLE
Fix style issues

### ISSUE THREAD

**Issue by miintTeaa** [foolbuffoon/T4Project#1]
Hello! This seems to be some kind of school project so I hope I'm not intruding by making an issue or something.

It would probably be a good idea to follow the python naming standard, or at least to keep the style consistent.

As an example, in [Logic.py](https://github.com/foolbuffoon/T4Project/blob/0fc12dfecf8c43f75f03e1aa79a7da4d740bac90/src/Logic.py), some variables use camelCase (ex. `gameStart` on line 12), some just go with all lowercase (ex.  `player` on line 14), and some go with snake_case (ex.  `art_logo` on line 21).

The standard is as follows:
- *snake_case* for **methods and variables**
- *UPPER_SNAKE_CASE* for **constant values** 
- *UpperCamelCase* for **classes**

Values should still (according to the standard) follow those style guides even if they are stored in a field.

Also, every field in [location.py](https://github.com/foolbuffoon/T4Project/blob/0fc12dfecf8c43f75f03e1aa79a7da4d740bac90/src/location.py) is prepended with loc, which seems unnecessary considering you know they all refer to a location since they're inside a `Location` object.

**Comment by foolbuffoon** [comment]
Fixed! Thank you for your input.

**Comment by foolbuffoon** [comment]
Ok, should actually be fixed now. Missed some stuff the first time, oops
